### ISSUE TITLE
在Windows平台架设Hexo并部署到Github Pages

### ISSUE THREAD

**Issue by ygbhf** [ygbhf/slash#2]
架设手记，为不会的网友提供一点帮助。

安装Node.js及Git-scm
---

在 [Node.js官网](http://nodejs.com) 下载及安装 Node.js ，在 [Git-scm官网](http://git-scm.com/download/win) 下载并安装 Git-scm ，直接按默认设置安装即可。

安装Hexo
---

在你想安装Hexo的目录下`右击`（例如 E:\Myblog ），点击 `Git Base Here` ，会弹出一个Git的窗口，在这个窗口里面依次输入：

```
npm install hexo -g  
hexo init  
npm install
```

    注意，在国内复杂的网络环境下，第一步可能会出现错误，如出现错误请挂上全局VPN  

建立Github仓库
---

前往 [Github](http://github.com) 注册并登录，新建一个名为 `您用户名.github.io` 的仓库（例如你注册的用户名是ygbhf，那么需要建立的仓库名称为 `ygbhf.github.io`）

建立好后获取您仓库的推送地址（形如 `https://github.com/ygbhf/ygbhf.github.io.git`）

设置并预览Hexo
---

然后修改当前目录下的 `_config.yml` 文件的相关内容，你可能需要修改的地方有：
```
# Site
title: #你博客的标题
subtitle: #你博客的副标题
description: #你博客的简介
author: #你的名字
email: #你的邮箱

# URL
url: #你博客的网址

# Disqus
disqus_shortname: #如果想启用评论的话，填写你注册的Disqus的名称

# Deployment
deploy:
   type: github
   repo: #你Github仓库的推送地址
   branch: master
   message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
```

设置好后，回到Git窗口，依次输入：

```
hexo s  #开启预览
```

	
在你本地浏览器输入 `localhost:4000` 即可预览你的Hexo博客

书写博客
---

在Git窗口输入：

```
hexo n "HelloWorld" #新建一篇标题为Hello World的文章
or
hexo n page "AboutMe" #新建一篇标题为About Me的单页面
```

然后在 `source\_posts` 下会出现一个 HelloWorld.md 的文件，使用文本文档编辑它即书写你的博客。

单页面会在 source 目录下 ，编辑 AboutMe\index.md 文件即可。

推送到Github
---

在Git窗口输入：
```
hexo g -d #g是生成，d是部署
```

随后输入你Github的用户，密码即可，即可推送到Github。

注意在第一次推送的时候可能要先输入以下命令来设置Git
```
git config --globle user.email "你的邮箱"
git config --globle user.name "你的名字"
```

----
更多请查看 [Hexo的官方文档](http://hexo.io/docs/)。
